Ocp maps/pen 42
spring-media/terraform-aws-vpc pull request #1
Opened 2024-08-15 11:56 UTC by as-extern-mbertram

This will add TGW subnets and creation of an attachment to the VPC module. Also naming is change for the resources to reflect the naming recommendations.

2024-08-22 07:57 UTC, plcoelho reviewed
Sorry for all of the remarks, but a lot of them are the same thing, just in different locations.
Let's have a conversation about them 😄

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +    { "Name" = "${var.name_prefix}-vpc${var.name_suffix}" },
I see we have a dash (`-`) between the _prefix_ and `vpc`, but not between the _suffix_ and `vpc`.
Should we not also have a dash (`-`) there? Or maybe not have the dash between the _prefix_ and `vpc`?
Just in terms of consistency I would have both or none.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        format("${var.name_prefix}%s-%s-sub-${var.public_subnet_suffix}",
Over here we have no dash (`-`) between the `name_prefix` and the next string, but we do have a dash before the _suffix_.
Is this the expected approach?

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        format("${var.name_prefix}%s-%s-sub-${var.public_subnet_suffix}",
Would also add a comment before with the naming convention, so the `format` becomes easier to understand:
`# ${var.name_prefix}<azname>-<azid>-sub-${var.public_subnet_suffix}`

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +          substr(element(var.azs, count.index), length(element(var.azs, count.index)) - 1, 1),
Am I reading the code wrong, or is this just grabbing the _letter_ associated with the _AZ_? I.E. if the _AZ_ is `euc1a`, this would grab the `a`, correct?
If that is the case, then two things:

1. We would directly add that _letter_ to the `name_prefix`, without being sure we have the region passed, which would cause some different naming shenanigans
2. We could reduce complexity by doing `substr(element(var.azs, count.index), - 1, 1)`
> The **offset index** may be **negative**, in which case it is **relative to the end** of the given string. The **length** may be **-1**, in which case the **remainder of the string** after the given offset will be returned.
> 
> https://developer.hashicorp.com/terraform/language/functions/substr

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +      ) : "${var.name_prefix}-rtb-${var.public_subnet_suffix}"
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        )
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +  # app1-test-euc1a-az2-sub-db
This should be removed.

We should instead have the following comment before line `258`:
`# ${var.name_prefix}<azname>-<azid>-sub-${var.public_subnet_suffix}`

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        )
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        )
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        substr(element(var.azs, count.index), length(element(var.azs, count.index)) - 1, 1),
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        )
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        )
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        )
Could we have used the `intra` subnets for our TGW Attachment subnets, instead of having to rewrite the code?
We would just pass `tgw-attachment` as a `intra_subnet_suffix`, right?

Also same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +      ) : "${var.name_prefix}-rtb-${var.intra_subnet_suffix}"
Also same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        )
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on main.tf
> +        )
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +  len_tgw_subnets         = max(length(var.tgw_subnets), length(var.private_subnet_ipv6_prefixes))
Replace `private_subnet_ipv6_prefixes` with `tgw_subnet_ipv6_prefixes`

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
I would recommend changing `tgw` to `tgw_att`, just to make it a bit clearer that this is the TGW attachment subnets.

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +  #substr(var.input_string, local.string_length - 1, 1)
This should be removed, right?

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +# There are as many routing tables as the number of NAT gateways
Is this correct?

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +  count = local.create_tgw_subnets && local.max_subnet_length > 0 ? local.nat_gateway_count : 0
I don't see how the NAT gateway plays a part here.

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +      "Name" = var.single_nat_gateway ? "${var.name_prefix}-${var.tgw_subnet_suffix}" : format(
I don't see how the NAT gateway plays a part here.

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +        "${var.name_prefix}%s-rtb-${var.tgw_subnet_suffix}",
Same remarks as the ones for lines `119` and `120`.

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +  count = (local.create_public_subnets && contains(local.subnets_tgw_routed, "public")) ? (var.enable_nat_gateway ? length(var.azs) : 1) : 0
Don't see how the NAT Gateway plays a role here.

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +  destination_prefix_list_id = can(regex("^pl-", var.transit_gateway_routes["public"])) ? var.transit_gateway_routes["public"] : null
I don't quite understand the `transit_gateway_routes` variable.
It seems like we can only create 1 route for public subnets. Am I misreading the code?

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
> +}
I believe these routes have the same `count` problem as the `public` routes.

2024-08-22 07:57 UTC, plcoelho commented on tgw.tf
I'm thinking if it would be better to have this in a separate Terraform module, instead of integrating it in the this module.
Let's talk about it.

2024-08-22 13:57 UTC, plcoelho requested changes

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +    { "Name" = "${var.name_prefix}-vpc${var.name_suffix}" },
Changes to do:
- Leave the first dash
- Add `-${var.region_shortcode}` after the first dash
- Add a dash before the `vpc_suffix`

2024-08-22 13:57 UTC, plcoelho commented on variables.tf
> +}
Change this to `vpc_suffix`, and make the default 'main'.

2024-08-22 13:57 UTC, plcoelho commented on variables.tf
> +}
Change this one to required (since it's already assumed that something is always passed).

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        format("${var.name_prefix}%s-%s-sub-${var.public_subnet_suffix}",
Changes:
- Add the after `${var.name_prefix}`
- Add `${var.region_shortcode}` after name_prefix

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +          substr(element(var.azs, count.index), length(element(var.azs, count.index)) - 1, 1),
First point gets solved with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
Still recommend doing the second point.

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +      ) : "${var.name_prefix}-rtb-${var.public_subnet_suffix}"
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        )
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        )
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        )
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        substr(element(var.azs, count.index), length(element(var.azs, count.index)) - 1, 1),
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        )
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        )
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        )
First point is clarified, we will have the separate subnet code.

Second point: we will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +      ) : "${var.name_prefix}-rtb-${var.intra_subnet_suffix}"
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**
-

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        )
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on main.tf
> +        )
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-22 13:57 UTC, plcoelho commented on tgw.tf
Talked with Marvin and we're keeping it like this!

2024-08-22 13:57 UTC, plcoelho commented on tgw.tf
> +  count = local.create_tgw_subnets && local.max_subnet_length > 0 ? local.nat_gateway_count : 0
In almost all cases we will have only 1 Route Table, but we do know of at least one exception to this, which is the inspection VPC.

For this reason we would do the following:
- Change `nat_gateway_count` to another local variable
- This local variable would have a default of `1`
- Except if we passed a value to a variable for the number of TGW Attachment Route Tables (something like `var.tgw_att_number_of_route_tables`

2024-08-22 13:57 UTC, plcoelho commented on tgw.tf
> +# There are as many routing tables as the number of NAT gateways
Remove this comment.

2024-08-22 13:57 UTC, plcoelho commented on tgw.tf
> +        "${var.name_prefix}%s-rtb-${var.tgw_subnet_suffix}",
We will add the comment before, to better show how the name is built.
We solve the remark from line `120` with the agreement of having `${var.name_prefix}-${var.region_shortcode}`.
- **So we need to add this part**

2024-08-27 11:31 UTC, gentgme commented on variables.tf
> +  type        = list(map(string))
The Var type should rather be list(map(object)) right?
At least the attribute values in the default are not all of type "string".
The same goes for the next variable.

2024-08-27 11:41 UTC, gentgme commented on variables.tf
> +variable "enable_tgw_nat_gateway" {
I don't think that I fully get what this variable is about.

2024-08-27 12:52 UTC, as-extern-mbertram commented on variables.tf
> +variable "enable_tgw_nat_gateway" {
Enabling routes in the TGW subnets to the NATGW

2024-08-27 12:55 UTC, as-extern-mbertram commented on variables.tf
> +  type        = list(map(string))
I think it is fine. It is also being done in the original module. Numbers are automatically converted to strings

2024-08-27 14:25 UTC, gentgme approved these changes

2024-08-27 16:14 UTC, plcoelho approved these changes
LGTM

2024-08-28 06:41 UTC, merged